### ISSUE TITLE
does not work(bad system call)

### ISSUE THREAD

**Issue by puddingepoch** [MasterDevX/Termux-Java#15]
this does not work at all
it just says bad system call
https://cdn.discordapp.com/attachments/370829069283098624/664754425574981662/Screenshot_20200109-035624.jpg
can you guys take this fake script down  i think its obvious youre ne er going to fix it a d its just waisti g everyones time

**Comment by ZooMMaX** [comment]
Install proot on termux and run java.

> apt install proot

> proot java -h

**Comment by MasterDevX** [comment]
@puddingepoch Hi there. First of all, stop calling things fake just because something is not working. Github is an open-source coding platform, what means you have full access to any project's code and you can easily see how this code works. So if you don't understand anything in this way, I recommend you just to stay away from this and think twice before opening a new issue next time. By the way, the solution of your problem was already found in https://github.com/MasterDevX/Termux-Java/issues/3 Closing this as duplicate, thanks.

**Comment by JSPVlad** [comment]
> @puddingepoch Hi there. First of all, stop calling things fake just because something is not working. Github is an open-source coding platform, what means you have full access to any project's code and you can easily see how this code works. So if you don't understand anything in this way, I recommend you just to stay away from this and think twice before opening a new issue next time. By the way, the solution of your problem was already found in #3 Closing this as duplicate, thanks.

Worked for me🤗
